Repository elastic/package-registry, pull requests merged in 2020-05, with the labels that each got.

#442 ci: Migrate job to JJBB
  .ci/Jenkinsfile
  .ci/defaults.yml
  .ci/package-registry.yml
Labels: [zube]: In Review, ci, team:automation

#443 ci: create JJBB folder
  .ci/jobs/defaults.yml
  .ci/jobs/package-registry.yml
Labels: bug, ci, team:automation

#458 ci: trigger the master job on changes on the master package registry
  .ci/Jenkinsfile
  .ci/jobs/package-registry.yml
Labels: ci, team:automation

#459 Add constant_keyword value to base templates
  dev/packages/example/base/0.2.0/elasticsearch/component-template/events-mappings.json
  dev/packages/example/base/0.2.0/elasticsearch/component-template/logs-mappings.json
  dev/packages/example/base/0.2.0/elasticsearch/component-template/metrics-mappings.json
Labels: Ingest Management:beta1

#428 Add kafka integration 0.0.2
  dev/import-beats-resources/kafka/docs/README.md
  dev/packages/alpha/kafka/0.0.2/dataset/broker/agent/stream/stream.yml.hbs
  dev/packages/alpha/kafka/0.0.2/dataset/broker/fields/fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/broker/fields/package-fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/broker/manifest.yml
  dev/packages/alpha/kafka/0.0.2/dataset/consumergroup/agent/stream/stream.yml.hbs
  dev/packages/alpha/kafka/0.0.2/dataset/consumergroup/fields/fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/consumergroup/fields/package-fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/consumergroup/manifest.yml
  dev/packages/alpha/kafka/0.0.2/dataset/log/agent/stream/log.yml.hbs
  dev/packages/alpha/kafka/0.0.2/dataset/log/elasticsearch/ingest-pipeline/default.yml
  dev/packages/alpha/kafka/0.0.2/dataset/log/fields/ecs.yml
  dev/packages/alpha/kafka/0.0.2/dataset/log/fields/fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/log/fields/package-fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/log/manifest.yml
  dev/packages/alpha/kafka/0.0.2/dataset/partition/agent/stream/stream.yml.hbs
  dev/packages/alpha/kafka/0.0.2/dataset/partition/fields/fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/partition/fields/package-fields.yml
  dev/packages/alpha/kafka/0.0.2/dataset/partition/manifest.yml
  dev/packages/alpha/kafka/0.0.2/docs/README.md
  dev/packages/alpha/kafka/0.0.2/img/filebeat-kafka-logs-overview.png
  dev/packages/alpha/kafka/0.0.2/img/logo_kafka.svg
  dev/packages/alpha/kafka/0.0.2/img/metricbeat_kafka_dashboard.png
  dev/packages/alpha/kafka/0.0.2/kibana/dashboard/943caca0-87ee-11e7-ad9c-db80de0bf8d3-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/dashboard/ea488d90-8e63-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/search/All Kafka logs-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/search/Kafka stacktraces-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/1681f1a0-90e7-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/27dd5960-d2ed-11e8-8766-dbbdc39e7ba9-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/3f7c33c0-87ee-11e7-ad9c-db80de0bf8d3-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/491fee50-d2f5-11e8-8766-dbbdc39e7ba9-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/587f2360-8f21-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/8d2f79a0-8e65-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/944188f0-8e79-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/9a7576e0-d231-11e8-8766-dbbdc39e7ba9-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/b9d12c80-8e63-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/dc89f8d0-8e8e-11e8-8fa2-3d5f811fbd0f-ecs.json
  dev/packages/alpha/kafka/0.0.2/kibana/visualization/number-of-kafka-stracktraces-by-class-ecs.json
  dev/packages/alpha/kafka/0.0.2/manifest.yml
Labels: [zube]: In Review, review

#402 Update Cisco integration
  dev/packages/alpha/cisco/0.0.3/dataset/asa/agent/stream/stream.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/asa/agent/stream/udp.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/asa/elasticsearch/ingest-pipeline/default.yml
  dev/packages/alpha/cisco/0.0.3/dataset/asa/fields/ecs.yml
  dev/packages/alpha/cisco/0.0.3/dataset/asa/fields/fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/asa/fields/package-fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/asa/manifest.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/agent/stream/stream.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/agent/stream/udp.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/elasticsearch/ingest-pipeline/default.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/fields/ecs.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/fields/fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/fields/package-fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ftd/manifest.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ios/agent/stream/stream.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/ios/agent/stream/syslog.yml.hbs
  dev/packages/alpha/cisco/0.0.3/dataset/ios/elasticsearch/ingest-pipeline/default.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ios/fields/ecs.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ios/fields/fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ios/fields/package-fields.yml
  dev/packages/alpha/cisco/0.0.3/dataset/ios/manifest.yml
  dev/packages/alpha/cisco/0.0.3/docs/README.md
  dev/packages/alpha/cisco/0.0.3/img/cisco.svg
  dev/packages/alpha/cisco/0.0.3/img/kibana-cisco-asa.png
  dev/packages/alpha/cisco/0.0.3/kibana/dashboard/a555b160-4987-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/search/14fce5e0-498f-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/search/753406e0-4986-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/search/96c6ff60-4986-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/08ef4d90-499b-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/118da960-4987-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/5d0322d0-4987-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/80d0c1b0-498a-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/a3b5ab10-4989-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/d05cdf60-498b-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/kibana/visualization/fd89b1e0-49a2-11e9-b8ce-ed898b5ef295.json
  dev/packages/alpha/cisco/0.0.3/manifest.yml
Labels: review

#476 chore: add team label to any PR
  .github/paths-labeller.yml
Labels: Team:Ingest Management, team:automation
