Repository elastic/package-registry, pull requests merged in 2020-06, with the labels that each got.

#483 Remove requirement for streams definition in dataset manifest
  CHANGELOG.md
  docs/api/categories-experimental.json
  docs/api/categories.json
  docs/api/search-all.json
  docs/api/search-category-logs.json
  docs/api/search-kibana652.json
  docs/api/search-kibana721.json
  docs/api/search-package-experimental.json
  docs/api/search-package-internal.json
  docs/api/search.json
  testdata/package/no_stream_configs/1.0.0/dataset/log/fields/ecs.yml
  testdata/package/no_stream_configs/1.0.0/dataset/log/manifest.yml
  testdata/package/no_stream_configs/1.0.0/docs/README.md
  testdata/package/no_stream_configs/1.0.0/manifest.yml
  testdata/public/package/no_stream_configs/1.0.0/dataset/log/fields/base-fields.yml
  testdata/public/package/no_stream_configs/1.0.0/dataset/log/fields/ecs.yml
  testdata/public/package/no_stream_configs/1.0.0/dataset/log/manifest.yml
  testdata/public/package/no_stream_configs/1.0.0/docs/README.md
  testdata/public/package/no_stream_configs/1.0.0/manifest.yml
  util/dataset.go
Labels: Team:ingest-management

#493 Basic integration test with Kibana
  .ci/Jenkinsfile
  magefile.go
  main_integration_test.go
  testing/environments/local.yml
Labels: Team:Ingest Management

#498 fix: correct path for JUnit test results
  .ci/Jenkinsfile
  .ci/jenkins-go-agent/Dockerfile
  go.mod
  go.sum
  magefile.go
Labels: bug, ci, team:automation

#542 feat: add labels to the Docker images
  .ci/Jenkinsfile
Labels: ci, enhancement, team:automation

#536 Add support for owner filed in package manifest
  CHANGELOG.md
  dev/packages/example/reference/1.0.0/manifest.yml
  docs/api/package.json
  docs/api/package/example/1.0.0/index.json
  testdata/package/example/1.0.0/manifest.yml
  util/package.go
Labels: Ingest Management:beta1

#534 Add additional categories
  CHANGELOG.md
  docs/api/categories-experimental.json
  docs/api/categories.json
  docs/api/package/default_pipeline/0.0.2/index.json
  testdata/package/default_pipeline/0.0.2/manifest.yml
  util/package.go
Labels: Ingest Management:beta1

#512 Add list of downloads to /search endpoint
  CHANGELOG.md
  docs/api/package.json
  docs/api/package/datasources/1.0.0/index.json
  docs/api/package/default_pipeline/0.0.2/index.json
  docs/api/package/ecs_style_dataset/0.0.1/index.json
  docs/api/package/example/0.0.2/index.json
  docs/api/package/example/1.0.0/index.json
  docs/api/package/experimental/0.0.1/index.json
  docs/api/package/foo/1.0.0/index.json
  docs/api/package/internal/1.2.0/index.json
  docs/api/package/multiple_false/0.0.1/index.json
  docs/api/package/no_stream_configs/1.0.0/index.json
  docs/api/search-all.json
  docs/api/search-category-logs.json
  docs/api/search-category-metrics.json
  docs/api/search-kibana652.json
  docs/api/search-kibana721.json
  docs/api/search-package-example-all.json
  docs/api/search-package-example.json
  docs/api/search-package-experimental.json
  docs/api/search-package-internal.json
  docs/api/search.json
  util/package.go
Labels: Ingest Management:beta1

#557 fix: remove duplicated files
  .ci/defaults.yml
  .ci/package-registry.yml
Labels: ci, team:automation

#532 Remove `removable` flag from package manifest
  CHANGELOG.md
  testdata/generated/package.json
  testdata/generated/package/base/0.2.0/index.json
  testdata/generated/package/datasources/1.0.0/index.json
  testdata/generated/package/default_pipeline/0.0.2/index.json
  testdata/generated/package/ecs_style_dataset/0.0.1/index.json
  testdata/generated/package/example/0.0.2/index.json
  testdata/generated/package/example/1.0.0/index.json
  testdata/generated/package/experimental/0.0.1/index.json
  testdata/generated/package/foo/1.0.0/index.json
  testdata/generated/package/internal/1.2.0/index.json
  testdata/generated/package/longdocs/1.0.4/index.json
  testdata/generated/package/metricsonly/2.0.1/index.json
  testdata/generated/package/multiple_false/0.0.1/index.json
  testdata/generated/package/multiversion/1.0.3/index.json
  testdata/generated/package/multiversion/1.0.4/index.json
  testdata/generated/package/multiversion/1.1.0/index.json
  testdata/generated/package/no_stream_configs/1.0.0/index.json
  testdata/generated/package/reference/1.0.0/index.json
  testdata/generated/package/yamlpipeline/1.0.0/index.json
  testdata/package/base/0.2.0/manifest.yml
  testdata/package/internal/1.2.0/manifest.yml
  util/package.go
Labels: Ingest Management:beta1

#514 Update package output structure
  testdata/generated/package.json
  testdata/generated/package/datasources/1.0.0/index.json
  testdata/generated/package/default_pipeline/0.0.2/index.json
  testdata/generated/package/ecs_style_dataset/0.0.1/index.json
  testdata/generated/package/example/1.0.0/index.json
  testdata/generated/package/multiple_false/0.0.1/index.json
  testdata/generated/package/no_stream_configs/1.0.0/index.json
  testdata/generated/package/reference/1.0.0/index.json
  testdata/generated/package/yamlpipeline/1.0.0/index.json
  testdata/package/example/1.0.0/dataset/foo/manifest.yml
  util/dataset.go
  util/package.go
Labels: Ingest Management:beta1

#567 Remove `dataset.type: event` as supported type.
  CHANGELOG.md
  util/dataset.go
Labels: Ingest Management:beta1
