Repository elastic/package-registry, pull requests merged in 2021-09, with the labels that each got.

#715 chore(ci): filter branches to monitor
  .ci/jobs/package-registry.yml
Labels: ci

#713 util: add `elasticsearch.privileges.indices`
  CHANGELOG.md
  testdata/generated/categories-experimental.json
  testdata/generated/categories-include-policy-templates.json
  testdata/generated/categories.json
  testdata/generated/package/elasticsearch_privileges/1.0.0/index.json
  testdata/generated/search-all.json
  testdata/generated/search-category-custom.json
  testdata/generated/search-package-experimental.json
  testdata/generated/search-package-internal.json
  testdata/generated/search.json
  testdata/package/elasticsearch_privileges/1.0.0/data_stream/elasticsearch_privileges/fields/base-fields.yml
  testdata/package/elasticsearch_privileges/1.0.0/data_stream/elasticsearch_privileges/manifest.yml
  testdata/package/elasticsearch_privileges/1.0.0/docs/README.md
  testdata/package/elasticsearch_privileges/1.0.0/manifest.yml
  util/data_stream.go
Labels: Team: Integrations

#729 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation

#735 [Fleet] Add categories to search response output
  .gitignore
  CHANGELOG.md
  testdata/generated/search-all.json
  testdata/generated/search-category-custom.json
  testdata/generated/search-category-datastore.json
  testdata/generated/search-category-web-all.json
  testdata/generated/search-category-web.json
  testdata/generated/search-kibana652.json
  testdata/generated/search-kibana721.json
  testdata/generated/search-package-example-all.json
  testdata/generated/search-package-example.json
  testdata/generated/search-package-experimental.json
  testdata/generated/search-package-internal.json
  testdata/generated/search.json
  util/package.go
Labels: enhancement, v8.0.0, v7.16.0

#734 Add 'constraints' and 'owner' to /search responses
  CHANGELOG.md
  categories.go
  index.go
  package_index.go
  search.go
  testdata/generated/categories-experimental.json
  testdata/generated/categories-include-policy-templates.json
  testdata/generated/categories-kibana652.json
  testdata/generated/categories.json
  testdata/generated/index.json
  testdata/generated/package.json
  testdata/generated/package/dataset_is_prefix/0.0.1/index.json
  testdata/generated/package/datasources/1.0.0/index.json
  testdata/generated/package/default_pipeline/0.0.2/index.json
  testdata/generated/package/ecs_style_dataset/0.0.1/index.json
  testdata/generated/package/elasticsearch_privileges/1.0.0/index.json
  testdata/generated/package/example/0.0.2/index.json
  testdata/generated/package/example/1.0.0/index.json
  testdata/generated/package/experimental/0.0.1/index.json
  testdata/generated/package/foo/1.0.0/index.json
  testdata/generated/package/hidden/1.0.0/index.json
  testdata/generated/package/ilm_policy/1.0.0/index.json
  testdata/generated/package/input_groups/0.0.1/index.json
  testdata/generated/package/input_level_templates/1.0.0/index.json
  testdata/generated/package/internal/1.2.0/index.json
  testdata/generated/package/longdocs/1.0.4/index.json
  testdata/generated/package/metricsonly/2.0.1/index.json
  testdata/generated/package/multiple_false/0.0.1/index.json
  testdata/generated/package/multiversion/1.0.3/index.json
  testdata/generated/package/multiversion/1.0.4/index.json
  testdata/generated/package/multiversion/1.1.0/index.json
  testdata/generated/package/no_stream_configs/1.0.0/index.json
  testdata/generated/package/reference/1.0.0/index.json
  testdata/generated/package/traces/1.0.0/index.json
  testdata/generated/package/yamlpipeline/1.0.0/index.json
  testdata/generated/search-all.json
  testdata/generated/search-category-custom.json
  testdata/generated/search-category-datastore.json
  testdata/generated/search-category-web-all.json
  testdata/generated/search-category-web.json
  testdata/generated/search-kibana652.json
  testdata/generated/search-kibana721.json
  testdata/generated/search-package-example-all.json
  testdata/generated/search-package-example.json
  testdata/generated/search-package-experimental.json
  testdata/generated/search-package-internal.json
  testdata/generated/search.json
  util/json.go
  util/package.go
  util/package_test.go
Labels: enhancement
